### ISSUE TITLE
Not Generating Metasploit Output

### ISSUE THREAD

**Issue by Dabuek** [silentbreaksec/ThrowbackLP#4]
After following the instructionals within the README of this I have verified apache, mssql and msf are working but the ThrowbackLP doesnt generate any binary payloads when requested? I just want to test its connectivity/usage ...

**Comment by silentbreaksec** [comment]
You have great timing. Tomorrow we'll be releasing an updated version and an install script. Stay tuned!

Sent from Outlook Mobilehttps://aka.ms/qtex0l

On Mon, Jan 25, 2016 at 5:33 AM -0800, "Pentestdan" <notifications@github.com<mailto:notifications@github.com>> wrote:

After following the instructionals within the README of this I have verified apache, mssql and msf are working but the ThrowbackLP doesnt generate any binary payloads when requested? I just want to test its connectivity/usage

##
